### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-9-#14]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Code is abstracted to functions with good function design

- [ ] There are cases of functions that have very obscure names and/or arguments. **- 1**

`feature_coef_table`

- [ ] Functions do not follow a consistent style. **-1**

- [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **- 1**

`rm_null`

- [ ] There are cases of functions with questionable internal design. **- 2**

`features`, `feature_coef_table`

### Functions are well documented

- [ ] Documentation does not follow a consistent style. **- 1**

### Helper data for tests is tractable and reproducible

- [ ] There are cases of tests that recreate the output manually instead of using simple known input and output. **- 1**

`rm_null`

- [ ] The data used could be a simple hand made data instead of the the original dataset.  **- 1**

`features`

### Tests suite is of high quality

- - [ ] There are cases of functions that do not test at least 1 edge-case input. **- 4**

`visualize_coefficients`, `rm_null`, `feature_coef_table`, `features`

- [ ] There are cases of functions that do not test at least 1 wrong input. **- 2**

`rm_null`, `features`

- [ ] There are cases of functions that do not test at least 2 expected input. **- 1**

`feature_coef_table`, `features`

### Dependencies have been updated (so it include the test libraries)

- [ ] Dependencie versions are not pinned. **- 1**

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 1**

`.ipynb_checkpoints`, `__pycache__`, etc

### GitHub Project board

- [ ] Project board is most effective when cards are converted to issues so that they can be assigned to collaborators, labeled and linked to milestones. **-1**

### GitHub Issue Milestones

- [ ]  GitHub issue milestones were not used for milestone 2. **- 2**
