### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-9-#42]
*Congratulations on finishing milestone 3! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [ ] One or more scripts are not well documented **- 4**

All of the scripts are missing documentation.

- [ ] One or more scripts are not well organized **- 1**

`src/model_car_data.py` has commneted out code

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2**

- [ ] The `Makefile` does not have a target for rendering the report. **- 5**

### Dependencies have been updated (so it include the test libraries)

- [ ] You have missing dependencies. **- 2**

Missing dependency for `make`

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 1**

`.ipynb_checkpoints`, `.virtual_documents/src`, `__pycache__`, etc

### GitHub Issue Milestones

- [ ] GitHub issue milestones were not used. **- 2**

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Analysis is essentially not reproducible. **- 13**

There are several problems with the reproducibility of the analysis.

- There is no instruction on how to run the analysis besides mentioning the jupyter file (not the objective for milestone 3). More specifically, there are no instructions on how to use `make`
- After opening the container, I tried to run `make all` and got `bash: make: command not found` which means that the environment has not been updated to support `make`
- Even after installing `make`, I got the following error when executing `make all`: `OSError: Cannot save file into a non-existent directory: 'data/csv`. There is similar error for `data/figures`
- There is neither a target on `Makefile` to render the report, nor instructions on how to render it.
