### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-9-#43]
*Congratulations on finishing your final project!!! This is a great accomplishment and you should be proud!
Below we list some specific feedback you can use to improve your project if you so desire,
but most importantly to learn.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Addressed feedback given by the teaching team from milestone 1

- [ ] 20% or less of the feedback given by the teaching team from milestone 1 was not addressed **-5**

The README got a few updates but the analysis is still no enough to make the anlaysis reproducible.

### Functional software package was created to share 3-4 functions that were written for the data analysis project.

- [ ] A package was created, but it is not in a separate repository and was not available in release made for milestone 4. **- 5**

### The software package is well documented

- [ ] A package was created, but it is not in a separate repository and was not available in release made for milestone 4. **- 2.5**

### The software package is robust (i.e., contains software tests for all package functions)

- [ ] A package was created, but it is not in a separate repository and was not available in release made for milestone 4. **- 2**

- [ ] It is missing vignette/tutorials docs. **- 1**

### Continuous integration is used to automate the running of software tests for the package functions

- [ ] There was no attempt. **- 5**

### Continous deployment is used to automate the building of the package documentation

- [ ] There was no attempt. **- 5**

### The software package has the correct file and directory structure, and recommended files for creating a package that is easy for others to use and contribute to

- [ ] A package was created, but it is not in a separate repository and was not available in release made for milestone 4. **- 2.5**

### Analysis code is updated such that it loads the functions from the newly created software package, instead of sourcing the functions from `.R` or `.py` files in the analysis project repository.

- [ ] A package was created, but it is not in a separate repository and was not available in release made for milestone 4. **- 0.5**

### Analysis code is updated such that unnecessary files are removed from the project repository (e.g., `.R` or `.py` files containing functions now loaded from the external software package, files containing tests for those functions, etc)

- [ ] A package was created, but it is not in a separate repository and was not available in release made for milestone 4. **- 0.5**

### Dependencies have been updated (so it include the newly created external software package)

- [ ] A package was created, but it is not in a separate repository and was not available in release made for milestone 4. **- 0.5**

### Project file and directory structure organization

- [ ] A package was created, but it is not in a separate repository and was not available in release made for milestone 4. **- 0.5**

### GitHub Issue Milestones

- [ ] GitHub issue milestones were not used. **- 1**

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-.5**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-1**

- [ ] Could not reproducibly run the analysis because there are no instructions. **-2.5**

- [ ] I got an error while trying to run `make all`. **- 2.5**

```
dsci-user@8a01a8b344cf:~/DSCI-310-Group-9-$ make all
python src/clean_car_data.py data/car.data data/csv/cleaned_data.csv
Traceback (most recent call last):
  File "/home/dsci-user/DSCI-310-Group-9-/src/clean_car_data.py", line 17, in <module>
    car_table.to_csv(args.out_file_path, index = False, header=False)
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 237, in save
    with get_handle(
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/c
```
