### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-9-#8]
*Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION`
(replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone).
This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

### README.md file

- [ ] Summary in README should include high-level interpretation of analysis findings,
as well 1-2 sentences on what they might mean (at least at a high-level). **-1**

### Analysis introduction

- [ ] The project should be asking a predictive question.
See https://datasciencebook.ca/intro.html#asking-a-question and https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/materials/lectures/01-intro-to-ds-workflows.html#revisiting-the-definition-of-data-science-what-is-the-question
for clarification if needed. **-1**
- [ ] The introduction should **identify** and **describe** the dataset that was used to answer the question. **-1**

### Analysis methods & results

- [ ] The data should be reproducibly downloaded from it's source using code in the analysis code document,
and a copy saved in the `data` directory (and ideally in the `data/raw` subdirectory. **-1**
- [ ] Narration of methods and method choices was not as clear and thorough as expected. **-1**
- [ ] Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. **-1**

### Analysis discussion

- [ ] The project should be asking a predictive question, and as a result,
the interpretations of the results should be reported and discussed in the context of a predictive question.
Interpretations should not be associative, inferential and certainly not causal; just predictive in nature.
See https://datasciencebook.ca/intro.html#asking-a-question
and https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/materials/lectures/01-intro-to-ds-workflows.html#revisiting-the-definition-of-data-science-what-is-the-question
for clarification if needed. **-1**

### Dockerfile

- [ ] The dependencie versions are not pinned. **-2**

### Project organization

- [ ] The analysis notebook (`*.ipynb`) should be in a sub-directory called something sensible, such as `analysis`,
`src`, `notebooks`, `docs`, etc, to aid in the discoverability of this file, and related ones.
Having too many files in the project root makes the project organization less understandable
and can lead to longer activation times to productivity for collaborators (including future you!). **-1**
- [ ] Files such as `.DS_Store` and `.ipynb_checkpoints` should not be committed. **-1**

### GitHub Project board

- [ ] Project board is most effective when cards are converted to issues so that they can be assigned to collaborators, labelled and linked to milestones. **-1**

### License

- [ ] Creative commons license needs to be included to specify how non-code/software work can be used, shared and derived. **-2**

### Follows GitHub flow version control workflow

- [ ] All contributions are expected to go through code review via a pull-request. **-2**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2**
- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**

### Team work contract

- [ ] Team work contract missing. **-5**

**Comment by lizhe918** [comment]
# Rectifications for Milestone 1
## Github Release
For this deduction, we cannot really change the submitted link on Canvas. So we provide the correct link here:
https://github.com/DSCI-310/DSCI-310-Group-9-/tree/v0.0.1

## README.md file
